### PR TITLE
Move backedge analysis here from Revise, add docs, and release 1.0

### PR DESCRIPTION
**Pull request by timholy**
Revise has had "backedge" analysis code for some time. It uses it to restrict the amount of code it needs to interpret in order to discover signatures. Unfortunately, it's been only partly successful, and the recent https://github.com/timholy/Revise.jl/issues/479 demonstrates that small tweaks can lead to big breakage.

This PR rewrites that entire code base and moves it from Revise to here. The old code relied on whole block-level decisions, whereas the new algorithm is granular to the level of individual statements. That means that it is more capable of stepping over lines that "do work" rather than define methods, even when the two are intermixed deep within an `@eval` (as is the case with AstroBase). I have verified that this, together with a suitably-rewritten Revise to be pushed later, fix (don't close yet) https://github.com/timholy/Revise.jl/issues/479 and seems to make Revise handle a wider variety of tricky code. CC @helgee. 

This also adds documentation. As you can see, this is a very large PR, though much of its size comes from splitting the original package up into several source files and adding documentation. Nevertheless the new `codeedges` file is sizable and bears almost no resemblance to its parent in Revise.

Once merged, I propose we call this the 1.0 release of LoweredCodeUtils.

~~Unfortunately there seems to be something messed up with my account so I don't have permissions to add the deploy key, we will want to get that figured out.~~

### CODE REVIEW

**Comment by KristofferC** [comment]
> Unfortunately there seems to be something messed up with my account so I don't have permissions to add the deploy key, we will want to get that figured out.


I see that a deploy key got added today by you.

**Comment by timholy** [comment]
Yeah, I don't know what was going on last nice.

Once this finishes building there should :crossed_fingers: be a preview of the docs at https://juliadebug.github.io/LoweredCodeUtils.jl/preview/PR30. I think you'll enjoy the "edges" page and especially the selective execution, @KristofferC.

For `print_with_code` you need https://github.com/JuliaLang/julia/pull/35952.

**Comment by KristofferC** [comment]
>  I think you'll enjoy the "edges" page and especially the selective execution, @KristofferC.

I am sure I will. I am bogged down in a project now so I haven't been able to fully enjoy and experiment with all the new method/code analysis progress you have made so much progress on. I mean to take a careful look at it in hopefully not too long.

**Comment by timholy** [comment]
Now with better precompiles, xref https://github.com/JuliaLang/julia/issues/34516#issuecomment-633080314

**Pull request merged**
