### PR TITLE
More robust signature-extraction

### PR DESCRIPTION
**Pull request by timholy**
This is a pretty significant overhaul to account for changes in JuliaInterpter's API, and in turn to revamp its own API to be more robust. The earlier implementations made a lot of assumptions about the precise sequence of statements in lowered code; it turns out that there is lots of real-world code that violated those assumptions.

I tested this more thoroughly using Base as a test case (those tests are not yet part of this package, they're currently living in my local rewrite of Revise, but they may move here eventually). With this PR and some additional helper code I can at least parse my way through all of Base without error. There are still a lot of missing signatures, so this is not "done," but it's definitely a milestone of sorts.

### CODE REVIEW

**Comment by timholy** [comment]
I am quite puzzled: AFAICT I've turned on Travis, but it's not running. Any insights?

**Comment by KristofferC** [comment]
Yes, no `.travis.yml` file :)

**Comment by timholy** [comment]
Doh! :laughing:

**Comment by timholy** [comment]
When I try to force-generate the manifest with
```julia
(v1) pkg> activate .

(LoweredCodeUtils) pkg> resolve
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package JuliaInterpreter [aa1ae85d]:
 JuliaInterpreter [aa1ae85d] log:
 ├─JuliaInterpreter [aa1ae85d] has no known versions!
 └─restricted to versions * by an explicit requirement — no versions left

(LoweredCodeUtils) pkg> dev https://github.com/JuliaDebug/JuliaInterpreter.jl.git
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Updating registry at `~/.julia/registries/HolyLabRegistry`
  Updating git-repo `git@github.com:HolyLab/HolyLabRegistry.git`
  Updating git-repo `https://github.com/JuliaDebug/JuliaInterpreter.jl.git`
[ Info: Path `/home/tim/.julia/dev/JuliaInterpreter` exists and looks like the correct package, using existing path
 Resolving package versions...
  Updating `~/.julia/dev/LoweredCodeUtils/Project.toml`
  [aa1ae85d] + JuliaInterpreter v0.1.1 [`~/.julia/dev/JuliaInterpreter`]
  Updating `~/.julia/dev/LoweredCodeUtils/Manifest.toml`
  [aa1ae85d] + JuliaInterpreter v0.1.1 [`~/.julia/dev/JuliaInterpreter`]
  [2a0f44e3] + Base64 
  [b77e0a4c] + InteractiveUtils 
  [d6f4376e] + Markdown 
  Building JuliaInterpreter → `~/.julia/dev/JuliaInterpreter/deps/build.log`
```
it encodes the literal path to my install, not the path I supplied. Is there an easy way to automatically generate a "commit-worthy" Manifest.toml?

**Comment by KristofferC** [comment]
Try using `add` instead of `dev`.

**Pull request merged**
