### PR TITLE
JuliaInterpeter 0.8 and various improvements

### PR DESCRIPTION
**Pull request by timholy**
Aside from compatibility, the most noteworthy improvement here is more systematic analysis in the initial `ismethod3` block of `methoddef!`. I think this fixes a longstanding bug in Revise that manifests via weird timing issues with logs.

### CODE REVIEW

**Comment by timholy** [comment]
Hmm, very strange compatibility error: Julia 1.5 and nightly both seem to claim that JuliaInterpreter 0.8 is not released.

Let's see if closing & reopening might work.

**Comment by timholy** [comment]
Hmm. I will wait until tomorrow and see whether there are any weird mirror issues that resolve themselves. FWIW locally I can install JuliaInterpreter 0.8 just fine.

**Comment by KristofferC** [comment]
It might friend on what server it picks to download the registry from, I think.

**Comment by timholy** [comment]
Did I screw up the `[compat]` string on JuliaInterpreter 0.8?
```
tim@diva:~/.julia/registries/General/J/JuliaInterpreter$ cat Compat.toml 
["0-0.7"]
julia = "1"

["0.2-0.7.13"]
CodeTracking = "0.3.2-0.5"

["0.7.14-0.7.20"]
CodeTracking = "0.5.9-0.5"

["0.7.21-0"]
CodeTracking = ["0.5.9-0.5", "1"]

["0.8-0"]
julia = ["1.0", "1.5.0-1"]
```

**Comment by KristofferC** [comment]
>  ├─possible versions are: [0.1.1, 0.2.0-0.2.1, 0.3.0-0.3.2, 0.4.0-0.4.1, 0.5.0-0.5.2, 0.6.0-0.6.1, 0.7.0-0.7.26] or uninstalled

means that the registry from that server doesn't contain 0.8 yet. Maybe something happened to the server.

**Comment by KristofferC** [comment]
Could always try by setting `JULIA_PKG_SERVER = ""` in Travis to get the registry via git.

**Comment by KristofferC** [comment]
Seems to be ok now.

**Pull request merged**
